# Generated by Django 4.2.1 on 2023-06-11 18:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0004_studentteacher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="teachers",
        ),
    ]
